apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: my-lovely-koa-app
  name: my-lovely-koa-app
  namespace: koa-app
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 3000
  selector:
    app: my-lovely-koa-app
  type: LoadBalancer
